version: "2"
services:
    nginx:
        image: nginx
        container_name: nginx # 容器名
        ports:
            - "80:80"
        volumes:
            - "/data/nginx/conf.d:/etc/nginx/conf.d"
            - "/data/nginx/data:/data"
        restart: always
